practice/Controllers/HomeController.cs
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using practice.Models;
using practice.Models.APIModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace practice.Controllers
{

    public class HomeController : Controller
    {
        private ProjectExampleEntities db = new ProjectExampleEntities();
        public string EventFeed(CalendarParameters model)
        {
            var userid = User.Identity.GetUserId();
            var sibling = db.Siblings.Find(userid);
            var startdate = DateTime.Parse("1970-01-01").AddMilliseconds(model.from);
            var enddate = DateTime.Parse("1970-01-01").AddMilliseconds(model.to);
            var UnavailableDates = sibling.SiblingGroup.Siblings.SelectMany(S => S.UnavailableDates).Where(u => u.Busydate >= startdate && u.Busydate <= enddate);
            var events = UnavailableDates.AsEnumerable().Select(u => new CalendarEvent(u));
            var maxbusyid = events.Any() ? events.Max(u => u.id):0;

            SiblingGroup siblingGroup;



            siblingGroup = sibling.SiblingGroup;



            var visits = siblingGroup.Visits.Where(v => v.VisitStart >= startdate && v.VisitStart <= enddate);
            var visitEvents = visits.AsEnumerable().Select(v => new CalendarEvent(v, maxbusyid * 1000));
            events = events.Concat(visitEvents);




            var apiresult = new CalendarAPIresult
            {
                success = 1,
                result = events.ToList()
            };
            var resultjson = JsonConvert.SerializeObject(apiresult);

            return resultjson;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Calendar()
        {
            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

practice/Controllers/UnavailableDatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using practice.Models;
using practice.Models.APIModels;

namespace practice.Controllers
{
    [Authorize(Roles = "Sibling")]
    public class UnavailableDatesController : Controller
    {
        private ProjectExampleEntities db = new ProjectExampleEntities();

        // GET: UnavailableDates
        public ActionResult Index()
        {
            return RedirectToAction("Calendar", "Home");
           
        }
        public ActionResult MyDates()
        {
            var userid = User.Identity.GetUserId();
            var sibling = db.Siblings.Find(userid);
            var UnavailableDates = sibling.UnavailableDates;
            return View(UnavailableDates.ToList());

        }

        // GET: UnavailableDates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UnavailableDate unavailableDate = db.UnavailableDates.Find(id);
            if (unavailableDate == null)
            {
                return HttpNotFound();
            }
            return View(unavailableDate);
        }

        // GET: UnavailableDates/Create
        public ActionResult Create()
        {
            var model = new UnavailableDate
            {
                SiblingId = User.Identity.GetUserId(),
                Busydate = DateTime.Today
            };
            return View(model);
        }

        // POST: UnavailableDates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SiblingId,Busydate")] UnavailableDate unavailableDate)
        {
            if (ModelState.IsValid)
            {
                db.UnavailableDates.Add(unavailableDate);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SiblingId = new SelectList(db.Siblings, "Id", "FirstName", unavailableDate.SiblingId);
            return View(unavailableDate);
        }

        // GET: UnavailableDates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UnavailableDate unavailableDate = db.UnavailableDates.Find(id);
            if (unavailableDate == null)
            {
                return HttpNotFound();
            }
            ViewBag.SiblingId = new SelectList(db.Siblings, "Id", "FirstName", unavailableDate.SiblingId);
            return View(unavailableDate);
        }

        // POST: UnavailableDates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SiblingId,Busydate")] UnavailableDate unavailableDate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(unavailableDate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MyDates");
            }
            ViewBag.SiblingId = new SelectList(db.Siblings, "Id", "FirstName", unavailableDate.SiblingId);
            return View(unavailableDate);
        }

        // GET: UnavailableDates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UnavailableDate unavailableDate = db.UnavailableDates.Find(id);
            if (unavailableDate == null)
            {
                return HttpNotFound();
            }
            return View(unavailableDate);
        }

        // POST: UnavailableDates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UnavailableDate unavailableDate = db.UnavailableDates.Find(id);
            db.UnavailableDates.Remove(unavailableDate);
            db.SaveChanges();
            return RedirectToAction("MyDates");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

practice/Controllers/VisitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using practice.Models;

namespace practice.Controllers
{
    [Authorize]
    public class VisitsController : Controller
    {
        private ProjectExampleEntities db = new ProjectExampleEntities();

        // GET: Visits
        public ActionResult Index(int? id)
        {
            SiblingGroup siblingGroup;
            if (User.IsInRole("Driver"))
            {
                siblingGroup = db.SiblingGroups.Find(id);
            }
            else
            {
                return RedirectToAction("Calendar", "Home");
                var userid = User.Identity.GetUserId();
                var Sibling = db.Siblings.Find(userid);
                siblingGroup = Sibling.SiblingGroup;

            }

            var visits = siblingGroup.Visits;
            return View(visits.ToList());
        }
        public ActionResult GroupVisits()
        {
            var userid = User.Identity.GetUserId();
            IEnumerable<Visit> Visits;
            if (User.IsInRole("Driver"))
            {
                var Driver = db.Drivers.Find(userid);
                Visits = Driver.Visits;
            }
            else
            {
              
               
                var Sibling = db.Siblings.Find(userid);
                
                var siblingGroup = Sibling.SiblingGroup;
                Visits = siblingGroup.Visits;
            }

           
            return View(Visits.ToList());
        }
    

        // GET: Visits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Find(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            return View(visit);
        }

        // GET: Visits/Create
        [Authorize (Roles = "Sibling")]
        public ActionResult Create()
        {
            ViewBag.DriverId = new SelectList(db.Drivers, "Id", "Name");
            var userId = User.Identity.GetUserId();
            var sibling = db.Siblings.Find(userId);
            var model = new Visit
            {
                GroupId = sibling.GroupId,
                VisitStart = DateTime.Now,
                VisitEnd = DateTime.Now.AddHours(3),
            };
            return View(model);
        }

        // POST: Visits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize (Roles = "Sibling")]
        public ActionResult Create([Bind(Include = "Id,VisitStart,VisitEnd,DriverId")] Visit visit)
        {
            var userid = User.Identity.GetUserId();
            var sibling = db.Siblings.Find(userid);
            var IsValid = ModelState.IsValid;
            if (IsValid && visit.VisitStart.Date != visit.VisitEnd.Date)
            {
                IsValid = false;
                ModelState.AddModelError("VisitEnd", "Visit Must Start and End on The Same Day");
            }
            if (IsValid && visit.VisitStart > visit.VisitEnd)
            {
                IsValid = false;
                ModelState.AddModelError("VisitEnd", "Visit End Date Is Prior Vist STart Date");
            }
            if (IsValid)
            {
               
                var UnavailableDates = sibling.SiblingGroup.Siblings.SelectMany(S => S.UnavailableDates).Select(D => D.Busydate);
                if(UnavailableDates.Any(D => D == visit.VisitStart.Date))
                {
                    IsValid = false;
                    ModelState.AddModelError("VisitStart", "Date is Not Available");
                }

            }
            if (IsValid)
            {
                var SiblingGroupId = sibling.GroupId;
                visit.GroupId = SiblingGroupId;
                db.Visits.Add(visit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DriverId = new SelectList(db.Drivers, "Id", "Name", visit.DriverId);
            ViewBag.GroupId = new SelectList(db.SiblingGroups, "Id", "Name", visit.GroupId);
            return View(visit);
        }

        // GET: Visits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Find(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            ViewBag.DriverId = new SelectList(db.Drivers, "Id", "Name", visit.DriverId);
            ViewBag.GroupId = new SelectList(db.SiblingGroups, "Id", "Name", visit.GroupId);
            return View(visit);
        }

        // POST: Visits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,GroupId,VisitStart,VisitEnd,DriverId")] Visit visit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(visit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DriverId = new SelectList(db.Drivers, "Id", "Name", visit.DriverId);
            ViewBag.GroupId = new SelectList(db.SiblingGroups, "Id", "Name", visit.GroupId);
            return View(visit);
        }

        // GET: Visits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Find(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            return View(visit);
        }

        // POST: Visits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Visit visit = db.Visits.Find(id);
            db.Visits.Remove(visit);
            db.SaveChanges();
            return RedirectToAction("GroupVisits");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

practice/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

practice/Views/Home/Calendar.cshtml
@using Microsoft.AspNet.Identity;
@model IEnumerable<practice.Models.UnavailableDate>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Unavailable Date", "Create", "UnavailableDates")
</p>
<p>
	@Html.ActionLink("Schedule Visit", "Create", "Visits")
</p>
<div class="btn-group">
    <button class="btn btn-primary" data-calendar-nav="prev">&lt;&lt; Prev</button>
    <button class="btn" data-calendar-nav="today">Today</button>
    <button class="btn btn-primary" data-calendar-nav="next">Next &gt;&gt;</button>
</div>
<div class="btn-group">
    <button class="btn btn-warning" data-calendar-view="year">Year</button>
    <button class="btn btn-warning active" data-calendar-view="month">Month</button>
    <button class="btn btn-warning" data-calendar-view="week">Week</button>
    <button class="btn btn-warning" data-calendar-view="day">Day</button>
</div>
<div id="calendarTitle">

</div>

<div id="calendar">

</div>
@section scripts{
    <script type="text/javascript">
 (function($) {


	var options = {
        events_source: '/home/eventfeed',
		view: 'month',
		tmpl_path: '/tmpls/',
		tmpl_cache: false,
		onAfterEventsLoad: function(events) {
			if(!events) {
				return;
			}
			var list = $('#eventlist');
			list.html('');

			$.each(events, function(key, val) {
				$(document.createElement('li'))
					.html('<a href="' + val.url + '">' + val.title + '</a>')
					.appendTo(list);
			});
		},
		onAfterViewLoad: function(view) {
			$('#calendarTitle').text(this.getTitle());
			$('.btn-group button').removeClass('active');
			$('button[data-calendar-view="' + view + '"]').addClass('active');
		},
		classes: {
			months: {
				general: 'label'
			}
		}
	};

	var calendar = $('#calendar').calendar(options);

	$('.btn-group button[data-calendar-nav]').each(function() {
		var $this = $(this);
		$this.click(function() {
			calendar.navigate($this.data('calendar-nav'));
		});
	});

	$('.btn-group button[data-calendar-view]').each(function() {
		var $this = $(this);
		$this.click(function() {
			calendar.view($this.data('calendar-view'));
		});
	});

	$('#first_day').change(function(){
		var value = $(this).val();
		value = value.length ? parseInt(value) : null;
		calendar.setOptions({first_day: value});
		calendar.view();
	});

	$('#language').change(function(){
		calendar.setLanguage($(this).val());
		calendar.view();
	});

	$('#events-in-modal').change(function(){
		var val = $(this).is(':checked') ? $(this).val() : null;
		calendar.setOptions({modal: val});
	});
	$('#format-12-hours').change(function(){
		var val = $(this).is(':checked') ? true : false;
		calendar.setOptions({format12: val});
		calendar.view();
	});
	$('#show_wbn').change(function(){
		var val = $(this).is(':checked') ? true : false;
		calendar.setOptions({display_week_numbers: val});
		calendar.view();
	});
	$('#show_wb').change(function(){
		var val = $(this).is(':checked') ? true : false;
		calendar.setOptions({weekbox: val});
		calendar.view();
	});
	$('#events-modal .modal-header, #events-modal .modal-footer').click(function(e){
		//e.preventDefault();
		//e.stopPropagation();
	});
}(jQuery));</script>
}

practice/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

practice/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

	<section>
		<p>
			<h2>While there is little national data on siblings in foster care, estimates indicate that well over half of children in foster care nationwide have one or more siblings also in care. Some sources state that as many as 75 percent of these foster children are placed apart from one or more of their siblings.</h2>
		</p>
		


	</section>